country_codes = {"BD": u"Bangladesh",
                 "BE": u"Belgium",
                 "BF": u"Burkina Faso",
                 "BG": u"Bulgaria",
                 "BA": u"Bosnia and Herzegovina",
                 "BB": u"Barbados",
                 "WF": u"Wallis and Futuna",
                 "BL": u"Saint Barthelemy",
                 "BM": u"Bermuda",
                 "BN": u"Brunei",
                 "BO": u"Bolivia",
                 "JP": u"Japan",
                 "BI": u"Burundi",
                 "BJ": u"Benin",
                 "BT": u"Bhutan",
                 "JM": u"Jamaica",
                 "BV": u"Bouvet Island",
                 "BW": u"Botswana",
                 "WS": u"Samoa",
                 "BQ": u"Bonaire, Sint Eustatius and Saba",
                 "BR": u"Brazil",
                 "BS": u"Bahamas",
                 "JE": u"Jersey",
                 "BY": u"Belarus",
                 "BZ": u"Belize",
                 "RU": u"Russia",
                 "RW": u"Rwanda",
                 "RS": u"Serbia",
                 "TL": u"Timor-Leste",
                 "RE": u"R\u00e9union",
                 "TM": u"Turkmenistan",
                 "TJ": u"Tajikistan",
                 "RO": u"Romania",
                 "TK": u"Tokelau",
                 "GW": u"Guinea-Bissau",
                 "GU": u"Guam",
                 "GT": u"Guatemala",
                 "GS": u"South Georgia and the South Sandwich Islands",
                 "GR": u"Greece",
                 "GQ": u"Equatorial Guinea",
                 "GP": u"Guadeloupe",
                 "BH": u"Bahrain",
                 "GY": u"Guyana",
                 "GG": u"Guernsey",
                 "GF": u"French Guiana",
                 "GE": u"Georgia",
                 "GD": u"Grenada",
                 "GB": u"United Kingdom",
                 "GA": u"Gabon",
                 "GN": u"Guinea",
                 "GM": u"Gambia",
                 "GL": u"Greenland",
                 "KW": u"Kuwait",
                 "GI": u"Gibraltar",
                 "GH": u"Ghana",
                 "OM": u"Oman",
                 "TN": u"Tunisia",
                 "JO": u"Jordan",
                 "HR": u"Croatia",
                 "HT": u"Haiti",
                 "HU": u"Hungary",
                 "HK": u"Hong Kong",
                 "HN": u"Honduras",
                 "HM": u"Heard Island and McDonald Islands",
                 "AD": u"Andorra",
                 "PR": u"Puerto Rico",
                 "PS": u"Palestinian Territory",
                 "PW": u"Palau",
                 "PT": u"Portugal",
                 "SJ": u"Svalbard",
                 "PY": u"Paraguay",
                 "AI": u"Anguilla",
                 "PA": u"Panama",
                 "PF": u"French Polynesia",
                 "PG": u"Papua New Guinea",
                 "PE": u"Peru",
                 "PK": u"Pakistan",
                 "PH": u"Philippines",
                 "PN": u"Pitcairn",
                 "PL": u"Poland",
                 "PM": u"Saint Pierre and Miquelon",
                 "ZM": u"Zambia",
                 "EH": u"Western Sahara",
                 "EE": u"Estonia",
                 "EG": u"Egypt",
                 "ZA": u"South Africa",
                 "EC": u"Ecuador",
                 "IT": u"Italy",
                 "AO": u"Angola",
                 "KZ": u"Kazakhstan",
                 "ET": u"Ethiopia",
                 "ZW": u"Zimbabwe",
                 "KY": u"Cayman Islands",
                 "ES": u"Spain",
                 "ER": u"Eritrea",
                 "ME": u"Montenegro",
                 "MD": u"Moldova",
                 "MG": u"Madagascar",
                 "MF": u"Saint Martin",
                 "MA": u"Morocco",
                 "MC": u"Monaco",
                 "UZ": u"Uzbekistan",
                 "MM": u"Myanmar",
                 "ML": u"Mali",
                 "MO": u"Macao",
                 "MN": u"Mongolia",
                 "MH": u"Marshall Islands",
                 "MK": u"Macedonia",
                 "UM": u"United States Minor Outlying Islands",
                 "MT": u"Malta",
                 "MW": u"Malawi",
                 "MV": u"Maldives",
                 "MQ": u"Martinique",
                 "MP": u"Northern Mariana Islands",
                 "MS": u"Montserrat",
                 "MR": u"Mauritania",
                 "AU": u"Australia",
                 "UG": u"Uganda",
                 "UA": u"Ukraine",
                 "MX": u"Mexico",
                 "VU": u"Vanuatu",
                 "FR": u"France",
                 "AW": u"Aruba",
                 "SH": u"Saint Helena Ascension and Tristan da Cunha",
                 "AF": u"Afghanistan",
                 "AX": u"\u00c5land Islands",
                 "FI": u"Finland",
                 "FJ": u"Fiji",
                 "FK": u"Falkland Islands",
                 "FM": u"Micronesia",
                 "FO": u"Faroe Islands",
                 "NI": u"Nicaragua",
                 "NL": u"Netherlands",
                 "NO": u"Norway",
                 "NA": u"Namibia",
                 "NC": u"New Caledonia",
                 "NE": u"Niger",
                 "NF": u"Norfolk Island",
                 "NG": u"Nigeria",
                 "NZ": u"New Zealand",
                 "NP": u"Nepal",
                 "NR": u"Nauru",
                 "NU": u"Niue",
                 "CK": u"Cook Islands",
                 "CI": u"Ivory Coast",
                 "CH": u"Switzerland",
                 "CO": u"Colombia",
                 "CN": u"China",
                 "CM": u"Cameroon",
                 "CL": u"Chile",
                 "CC": u"Cocos Islands",
                 "CA": u"Canada",
                 "CG": u"Congo Republic",
                 "CF": u"Central African Republic",
                 "CD": u"Congo Democratic Republic",
                 "CZ": u"Czech Republic",
                 "CY": u"Cyprus",
                 "CX": u"Christmas Island",
                 "CR": u"Costa Rica",
                 "CW": u"Cura\u00e7ao",
                 "CV": u"Cape Verde",
                 "CU": u"Cuba",
                 "SZ": u"Swaziland",
                 "SY": u"Syria",
                 "SX": u"Sint Maarten",
                 "KG": u"Kyrgyzstan",
                 "KE": u"Kenya",
                 "SR": u"Suriname",
                 "KI": u"Kiribati",
                 "KH": u"Cambodia",
                 "SV": u"El Salvador",
                 "KM": u"Comoros",
                 "ST": u"Sao Tome and Principe",
                 "SK": u"Slovakia",
                 "KR": u"Korea South",
                 "SI": u"Slovenia",
                 "KP": u"Korea North",
                 "SO": u"Somalia",
                 "SN": u"Senegal",
                 "SM": u"San Marino",
                 "SL": u"Sierra Leone",
                 "SC": u"Seychelles",
                 "SB": u"Solomon Islands",
                 "SA": u"Saudi Arabia",
                 "SG": u"Singapore",
                 "SE": u"Sweden",
                 "SD": u"Sudan",
                 "DO": u"Dominican Republic",
                 "DM": u"Dominica",
                 "DJ": u"Djibouti",
                 "DK": u"Denmark",
                 "DE": u"Germany",
                 "YE": u"Yemen",
                 "AT": u"Austria",
                 "DZ": u"Algeria",
                 "US": u"United States",
                 "UY": u"Uruguay",
                 "YT": u"Mayotte",
                 "MU": u"Mauritius",
                 "KN": u"Saint Kitts and Nevis",
                 "TZ": u"Tanzania",
                 "LC": u"Saint Lucia",
                 "LA": u"Laos",
                 "TV": u"Tuvalu",
                 "TW": u"Taiwan",
                 "TT": u"Trinidad and Tobago",
                 "TR": u"Turkey",
                 "LK": u"Sri Lanka",
                 "LI": u"Liechtenstein",
                 "LV": u"Latvia",
                 "TO": u"Tonga",
                 "LT": u"Lithuania",
                 "LU": u"Luxembourg",
                 "LR": u"Liberia",
                 "LS": u"Lesotho",
                 "TH": u"Thailand",
                 "TF": u"French Southern Territories",
                 "TG": u"Togo",
                 "TD": u"Chad",
                 "TC": u"Turks and Caicos Islands",
                 "LY": u"Libya",
                 "VA": u"Holy See",
                 "VC": u"Saint Vincent and the Grenadines",
                 "AE": u"United Arab Emirates",
                 "VE": u"Venezuela",
                 "AG": u"Antigua and Barbuda",
                 "VG": u"British Virgin Islands",
                 "IQ": u"Iraq",
                 "VI": u"Virgin Islands",
                 "IS": u"Iceland",
                 "IR": u"Iran",
                 "AM": u"Armenia",
                 "AL": u"Albania",
                 "VN": u"Vietnam",
                 "AQ": u"Antarctica",
                 "AS": u"American Samoa",
                 "AR": u"Argentina",
                 "IM": u"Isle of Man",
                 "IL": u"Israel",
                 "IO": u"British Indian Ocean Territory",
                 "IN": u"India",
                 "LB": u"Lebanon",
                 "AZ": u"Azerbaijan",
                 "IE": u"Ireland",
                 "ID": u"Indonesia",
                 "MY": u"Malaysia",
                 "QA": u"Qatar",
                 "MZ": u"Mozambique"}
